import Head from 'next/head'

import Hero from '../components/homepage/Hero'
import LatestBlog from '../components/homepage/LatestBlog'
import Banner from '../components/homepage/Banner'
import Projects from '../components/homepage/Projects'

export default function Home() {
  return (
    <>
      <Head>
        <title>Code Hostel- Alok Verma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <LatestBlog />
      <Banner />
      <Projects />
    </>
  )
}
