import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Code Hostel- Alok Verma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Hero section */}
      <section className="bg-gray-900 text-white">
        <div
          className="mx-auto max-w-screen-xl px-4 py-32 lg:flex lg:h-screen lg:items-center"
        >
          <div className="mx-auto max-w-3xl text-center">
            <h1
              className="bg-gradient-to-r from-green-300 via-blue-500 to-purple-600 bg-clip-text text-3xl font-extrabold text-transparent sm:text-5xl"
            >
              Crafting digital solutions
              <span className="sm:block"> with code and creativity. </span>
            </h1>

            <p className="mx-auto mt-4 max-w-xl sm:text-xl sm:leading-relaxed">
              Welcome to my web development services! I strive to meet your unique needs and exceed your expectations with top-quality work. Contact me today to see how I can help your online presence succeed.
            </p>

            <div className="mt-8 flex flex-wrap justify-center gap-4">
              <a
                className="block w-full rounded border border-blue-600 bg-blue-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-white focus:outline-none focus:ring active:text-opacity-75 sm:w-auto"
                href="/get-started"
              >
                Get Started
              </a>

              <Link
                className="block w-full rounded border border-blue-600 px-12 py-3 text-sm font-medium text-white hover:bg-blue-600 focus:outline-none focus:ring active:bg-blue-500 sm:w-auto"
                href="/about"
              >
                Learn More
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Latest Blog */}
      <section className="py-6 sm:py-12 dark:bg-gray-800 dark:text-gray-100">
        <div className="container p-6 mx-auto space-y-8">
          <div className="space-y-2 text-center">
            <h2 className="text-3xl font-bold">Latest Blogs</h2>
            <p className="font-serif text-sm dark:text-gray-400">Have a look on my latest published blogs.</p>
          </div>
          <div className="grid grid-cols-1 gap-x-4 gap-y-8 md:grid-cols-2 lg:grid-cols-4">
            <article className="flex flex-col dark:bg-gray-900">
              <a
                href="#"
                className="relative block overflow-hidden rounded-lg border border-gray-100 p-8"
              >
                <span
                  className="absolute inset-x-0 bottom-0 h-2 bg-gradient-to-r from-green-300 via-blue-500 to-purple-600"
                ></span>

                <div className="justify-between sm:flex">
                  <div>
                    <h3 className="text-xl font-bold text-gray-900">
                      Building a SaaS product as a software developer
                    </h3>

                    <p className="mt-1 text-xs font-medium text-gray-600">By John Doe</p>
                  </div>

                  <div className="ml-3 hidden flex-shrink-0 sm:block">
                    <img
                      alt="Paul Clapton"
                      src="https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1180&q=80"
                      className="h-16 w-16 rounded-lg object-cover shadow-sm"
                    />
                  </div>
                </div>

                <div className="mt-4 sm:pr-8">
                  <p className="text-sm text-gray-500">
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. At velit illum
                    provident a, ipsa maiores deleniti consectetur nobis et eaque.
                  </p>
                </div>

                <dl className="mt-6 flex">
                  <div className="flex flex-col-reverse">
                    <dt className="text-sm font-medium text-gray-600">Published</dt>
                    <dd className="text-xs text-gray-500">31st June, 2021</dd>
                  </div>

                  <div className="ml-3 flex flex-col-reverse sm:ml-6">
                    <dt className="text-sm font-medium text-gray-600">Reading time</dt>
                    <dd className="text-xs text-gray-500">3 minute</dd>
                  </div>
                </dl>
              </a>

            </article>
            <article className="flex flex-col dark:bg-gray-900">
              <a
                href="#"
                className="relative block overflow-hidden rounded-lg border border-gray-100 p-8"
              >
                <span
                  className="absolute inset-x-0 bottom-0 h-2 bg-gradient-to-r from-green-300 via-blue-500 to-purple-600"
                ></span>

                <div className="justify-between sm:flex">
                  <div>
                    <h3 className="text-xl font-bold text-gray-900">
                      Building a SaaS product as a software developer
                    </h3>

                    <p className="mt-1 text-xs font-medium text-gray-600">By John Doe</p>
                  </div>

                  <div className="ml-3 hidden flex-shrink-0 sm:block">
                    <img
                      alt="Paul Clapton"
                      src="https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1180&q=80"
                      className="h-16 w-16 rounded-lg object-cover shadow-sm"
                    />
                  </div>
                </div>

                <div className="mt-4 sm:pr-8">
                  <p className="text-sm text-gray-500">
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. At velit illum
                    provident a, ipsa maiores deleniti consectetur nobis et eaque.
                  </p>
                </div>

                <dl className="mt-6 flex">
                  <div className="flex flex-col-reverse">
                    <dt className="text-sm font-medium text-gray-600">Published</dt>
                    <dd className="text-xs text-gray-500">31st June, 2021</dd>
                  </div>

                  <div className="ml-3 flex flex-col-reverse sm:ml-6">
                    <dt className="text-sm font-medium text-gray-600">Reading time</dt>
                    <dd className="text-xs text-gray-500">3 minute</dd>
                  </div>
                </dl>
              </a>
            </article>
            <article className="flex flex-col dark:bg-gray-900">
              <a
                href="#"
                className="relative block overflow-hidden rounded-lg border border-gray-100 p-8"
              >
                <span
                  className="absolute inset-x-0 bottom-0 h-2 bg-gradient-to-r from-green-300 via-blue-500 to-purple-600"
                ></span>

                <div className="justify-between sm:flex">
                  <div>
                    <h3 className="text-xl font-bold text-gray-900">
                      Building a SaaS product as a software developer
                    </h3>

                    <p className="mt-1 text-xs font-medium text-gray-600">By John Doe</p>
                  </div>

                  <div className="ml-3 hidden flex-shrink-0 sm:block">
                    <img
                      alt="Paul Clapton"
                      src="https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1180&q=80"
                      className="h-16 w-16 rounded-lg object-cover shadow-sm"
                    />
                  </div>
                </div>

                <div className="mt-4 sm:pr-8">
                  <p className="text-sm text-gray-500">
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. At velit illum
                    provident a, ipsa maiores deleniti consectetur nobis et eaque.
                  </p>
                </div>

                <dl className="mt-6 flex">
                  <div className="flex flex-col-reverse">
                    <dt className="text-sm font-medium text-gray-600">Published</dt>
                    <dd className="text-xs text-gray-500">31st June, 2021</dd>
                  </div>

                  <div className="ml-3 flex flex-col-reverse sm:ml-6">
                    <dt className="text-sm font-medium text-gray-600">Reading time</dt>
                    <dd className="text-xs text-gray-500">3 minute</dd>
                  </div>
                </dl>
              </a>
            </article>
            <article className="flex flex-col dark:bg-gray-900">
              <a
                href="#"
                className="relative block overflow-hidden rounded-lg border border-gray-100 p-8"
              >
                <span
                  className="absolute inset-x-0 bottom-0 h-2 bg-gradient-to-r from-green-300 via-blue-500 to-purple-600"
                ></span>

                <div className="justify-between sm:flex">
                  <div>
                    <h3 className="text-xl font-bold text-gray-900">
                      Building a SaaS product as a software developer
                    </h3>

                    <p className="mt-1 text-xs font-medium text-gray-600">By John Doe</p>
                  </div>

                  <div className="ml-3 hidden flex-shrink-0 sm:block">
                    <img
                      alt="Paul Clapton"
                      src="https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1180&q=80"
                      className="h-16 w-16 rounded-lg object-cover shadow-sm"
                    />
                  </div>
                </div>

                <div className="mt-4 sm:pr-8">
                  <p className="text-sm text-gray-500">
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. At velit illum
                    provident a, ipsa maiores deleniti consectetur nobis et eaque.
                  </p>
                </div>

                <dl className="mt-6 flex">
                  <div className="flex flex-col-reverse">
                    <dt className="text-sm font-medium text-gray-600">Published</dt>
                    <dd className="text-xs text-gray-500">31st June, 2021</dd>
                  </div>

                  <div className="ml-3 flex flex-col-reverse sm:ml-6">
                    <dt className="text-sm font-medium text-gray-600">Reading time</dt>
                    <dd className="text-xs text-gray-500">3 minute</dd>
                  </div>
                </dl>
              </a>

            </article>
          </div>
        </div>
      </section>

      {/* Banner */}
      <div className="p-6 py-12 bg-[#004aad] dark:bg-indigo-400 dark:text-gray-900">
        <div className="container mx-auto text-white">
          <div className="flex flex-col lg:flex-row items-center justify-between">
            <h2 className="text-center text-6xl tracking-tighter font-bold">Up to
              <br className="sm:hidden" /> 50% Off
            </h2>
            <div className="space-x-2 text-center py-2 lg:py-0">
              <span>Plus free shipping! Use code:</span>
              <span className="font-bold text-lg">MAMBA</span>
            </div>
            <a href="#" rel="noreferrer noopener" className="px-5 mt-4 lg:mt-0 py-3 rounded-md border block dark:bg-gray-50 dark:text-gray-900 dark:border-gray-400">Shop Now</a>
          </div>
        </div>
      </div>


      {/* Projects */}
      <section>
        <div className="max-w-screen-xl px-4 py-8 mx-auto sm:py-12 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 gap-4 lg:grid-cols-3 lg:items-stretch">
            <div className="grid p-6 bg-gray-100 rounded place-content-center sm:p-8">
              <div className="max-w-md mx-auto text-center lg:text-left">
                <header>
                  <h2 className="text-xl font-bold text-gray-900 sm:text-3xl">Watches</h2>

                  <p className="mt-4 text-gray-500">
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas
                    rerum quam amet provident nulla error!
                  </p>
                </header>

                <a
                  href="#"
                  className="inline-block px-12 py-3 mt-8 text-sm font-medium text-white transition bg-gray-900 border border-gray-900 rounded hover:shadow focus:outline-none focus:ring"
                >
                  Shop All
                </a>
              </div>
            </div>
            <div className="lg:col-span-2 lg:py-8">
              <ul className="grid grid-cols-2 gap-4">
                <li>
                  <a href="#" className="block group">
                    <img
                      src="https://images.unsplash.com/photo-1523275335684-37898b6baf30?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1598&q=80"
                      alt=""
                      className="object-cover w-full rounded aspect-square"
                    />

                    <div className="mt-3">
                      <h3
                        className="font-medium text-gray-900 group-hover:underline group-hover:underline-offset-4"
                      >
                        Simple Watch
                      </h3>

                      <p className="mt-1 text-sm text-gray-700">$150</p>
                    </div>
                  </a>
                </li>

                <li>
                  <a href="#" className="block group">
                    <img
                      src="https://images.unsplash.com/photo-1523275335684-37898b6baf30?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1598&q=80"
                      alt=""
                      className="object-cover w-full rounded aspect-square"
                    />

                    <div className="mt-3">
                      <h3
                        className="font-medium text-gray-900 group-hover:underline group-hover:underline-offset-4"
                      >
                        Simple Watch
                      </h3>

                      <p className="mt-1 text-sm text-gray-700">$150</p>
                    </div>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}
